#!/usr/bin/env python3
"""Deterministic hand-edit detection for auto-generated files with a hash sidecar.

tracking/learned-preferences.md is regenerated by /learn-preferences, /applied,
and /import-applications, but a user may hand-edit it between runs. Detecting
that (so the next auto-write asks before clobbering) is pure hash comparison
-- this script owns it so all three callers agree on exactly what "hand-edited"
means instead of each re-describing the same shasum-and-compare steps.

Usage:
    python3 scripts/hash_sidecar.py check --file tracking/learned-preferences.md \\
        --sidecar tracking/.learned-preferences.hash
    python3 scripts/hash_sidecar.py write --file tracking/learned-preferences.md \\
        --sidecar tracking/.learned-preferences.hash
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path


def _hash_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def cmd_check(args) -> None:
    file_path = Path(args.file)
    sidecar_path = Path(args.sidecar)

    if not file_path.exists() or not sidecar_path.exists():
        print(json.dumps({"first_time": True, "hand_edited": False}, indent=2))
        return

    current_hash = _hash_file(file_path)
    recorded_hash = sidecar_path.read_text().strip()
    result = {
        "first_time": False,
        "hand_edited": current_hash != recorded_hash,
    }
    print(json.dumps(result, indent=2))


def cmd_write(args) -> None:
    file_path = Path(args.file)
    sidecar_path = Path(args.sidecar)
    digest = _hash_file(file_path)
    sidecar_path.write_text(digest + "\n")
    print(json.dumps({"hash": digest}, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(description="Hand-edit detection via a hash sidecar file.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_check = sub.add_parser("check", help="Check whether --file has changed since --sidecar was last written.")
    p_check.add_argument("--file", required=True)
    p_check.add_argument("--sidecar", required=True)
    p_check.set_defaults(func=cmd_check)

    p_write = sub.add_parser("write", help="Hash --file and write the digest to --sidecar.")
    p_write.add_argument("--file", required=True)
    p_write.add_argument("--sidecar", required=True)
    p_write.set_defaults(func=cmd_write)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    sys.exit(main())
